# Generated by Django 2.2.6 on 2019-12-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rating', models.CharField(choices=[('E', 'Exellent'), ('V', 'Very Good'), ('G', 'Good'), ('B', 'Bad')], default=('E', 'Exellent'), max_length=1)),
            ],
        ),
    ]
