# Generated by Django 2.2.6 on 2019-12-20 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Movie'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('E', 'Exellent'), ('V', 'Very Good'), ('G', 'Good'), ('B', 'Bad')], default='E', max_length=1),
        ),
    ]
